name: Node.js Publish

on:
    release:
        types: [created]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  registry-url: https://registry.npmjs.org/
            - run: npm install -g npm
            - run: npm ci
            - run: npm run build
            - run: rm -fdr node_modules && npm -g i husky && npm i --omit=dev
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
